name: huy_resume
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
# consider running `flutter pub upgrade --major-versions`
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  build_runner: 2.4.7
flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    
    - family: DINPro Black
      fonts:
        - asset: assets/fonts/dinpro/DINPro-Black.ttf
    - family: DINPro Bold
      fonts:
        - asset: assets/fonts/dinpro/DINPro-Bold.ttf
    - family: DINPro Light
      fonts:
        - asset: assets/fonts/dinpro/DINPro-Light.ttf
    - family: DINPro Medium
      fonts:
        - asset: assets/fonts/dinpro/DINPro-Medium.ttf
